// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dish_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_DishModel _$DishModelFromJson(Map<String, dynamic> json) => _DishModel(
  id: (json['id'] as num?)?.toInt(),
  restaurant_id: (json['restaurant_id'] as num?)?.toInt(),
  dish_category_id: (json['dish_category_id'] as num?)?.toInt(),
  parent_dish_id: (json['parent_dish_id'] as num?)?.toInt(),
  is_parent: json['is_parent'] as bool?,
  name: json['name'] as String?,
  price: (json['price'] as num?)?.toDouble(),
  acm_price: (json['acm_price'] as num?)?.toDouble(),
  exclude_from_offer: json['exclude_from_offer'] as bool?,
  exclude_from_web: json['exclude_from_web'] as bool?,
  status: json['status'] as bool?,
  sort_order: (json['sort_order'] as num?)?.toInt(),
  is_favorite: json['is_favorite'] as bool?,
  short_name: json['short_name'] as String?,
  takeaway_dish_code: json['takeaway_dish_code'] as String?,
  dine_in_dish_code: json['dine_in_dish_code'] as String?,
  group_id: (json['group_id'] as num?)?.toInt(),
  group_id_1: (json['group_id_1'] as num?)?.toInt(),
  group_id_2: (json['group_id_2'] as num?)?.toInt(),
  group_id_3: (json['group_id_3'] as num?)?.toInt(),
  printer_zone_setup_id: (json['printer_zone_setup_id'] as num?)?.toInt(),
  server_id: (json['server_id'] as num?)?.toInt(),
  category_print_order: (json['category_print_order'] as num?)?.toInt(),
  alternative_dish_name: json['alternative_dish_name'] as String?,
  dish_description: json['dish_description'] as String?,
  dish_name: json['dish_name'] as String?,
  hide_on_takeaway: json['hide_on_takeaway'] as bool?,
  hide_on_table: json['hide_on_table'] as bool?,
  printer_zone_setup_id_1: (json['printer_zone_setup_id_1'] as num?)?.toInt(),
  printer_zone_setup_id_2: (json['printer_zone_setup_id_2'] as num?)?.toInt(),
  expiry_date: (json['expiry_date'] as num?)?.toInt(),
  pack_size: (json['pack_size'] as num?)?.toInt(),
  allergens: json['allergens'] as String?,
  is_enable_vat: json['is_enable_vat'] as bool?,
  print_order: (json['print_order'] as num?)?.toInt(),
  show_option_auto: json['show_option_auto'] as bool?,
  vat_rate: (json['vat_rate'] as num?)?.toDouble(),
  dine_in_vat_rate: (json['dine_in_vat_rate'] as num?)?.toDouble(),
  is_vat_included: json['is_vat_included'] as bool?,
  is_dish_extras: json['is_dish_extras'] as bool?,
  takeaway_vat_percent: (json['takeaway_vat_percent'] as num?)?.toDouble(),
  dine_in_vat_percent: (json['dine_in_vat_percent'] as num?)?.toDouble(),
  takeaway_vat_amount: (json['takeaway_vat_amount'] as num?)?.toDouble(),
  dine_in_vat_amount: (json['dine_in_vat_amount'] as num?)?.toDouble(),
  offer_discount_id: (json['offer_discount_id'] as num?)?.toInt(),
);

Map<String, dynamic> _$DishModelToJson(_DishModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'restaurant_id': instance.restaurant_id,
      'dish_category_id': instance.dish_category_id,
      'parent_dish_id': instance.parent_dish_id,
      'is_parent': instance.is_parent,
      'name': instance.name,
      'price': instance.price,
      'acm_price': instance.acm_price,
      'exclude_from_offer': instance.exclude_from_offer,
      'exclude_from_web': instance.exclude_from_web,
      'status': instance.status,
      'sort_order': instance.sort_order,
      'is_favorite': instance.is_favorite,
      'short_name': instance.short_name,
      'takeaway_dish_code': instance.takeaway_dish_code,
      'dine_in_dish_code': instance.dine_in_dish_code,
      'group_id': instance.group_id,
      'group_id_1': instance.group_id_1,
      'group_id_2': instance.group_id_2,
      'group_id_3': instance.group_id_3,
      'printer_zone_setup_id': instance.printer_zone_setup_id,
      'server_id': instance.server_id,
      'category_print_order': instance.category_print_order,
      'alternative_dish_name': instance.alternative_dish_name,
      'dish_description': instance.dish_description,
      'dish_name': instance.dish_name,
      'hide_on_takeaway': instance.hide_on_takeaway,
      'hide_on_table': instance.hide_on_table,
      'printer_zone_setup_id_1': instance.printer_zone_setup_id_1,
      'printer_zone_setup_id_2': instance.printer_zone_setup_id_2,
      'expiry_date': instance.expiry_date,
      'pack_size': instance.pack_size,
      'allergens': instance.allergens,
      'is_enable_vat': instance.is_enable_vat,
      'print_order': instance.print_order,
      'show_option_auto': instance.show_option_auto,
      'vat_rate': instance.vat_rate,
      'dine_in_vat_rate': instance.dine_in_vat_rate,
      'is_vat_included': instance.is_vat_included,
      'is_dish_extras': instance.is_dish_extras,
      'takeaway_vat_percent': instance.takeaway_vat_percent,
      'dine_in_vat_percent': instance.dine_in_vat_percent,
      'takeaway_vat_amount': instance.takeaway_vat_amount,
      'dine_in_vat_amount': instance.dine_in_vat_amount,
      'offer_discount_id': instance.offer_discount_id,
    };
