// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'contactless_order_token_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_ContactlessOrderTokenModel _$ContactlessOrderTokenModelFromJson(
  Map<String, dynamic> json,
) => _ContactlessOrderTokenModel(
  id: json['id'] as String?,
  internalId: json['_id'] as String?,
  server_id: (json['server_id'] as num?)?.toInt(),
  status: json['status'] as bool?,
  restaurant_order_policy_id: (json['restaurant_order_policy_id'] as num?)
      ?.toInt(),
  total_amount: (json['total_amount'] as num?)?.toDouble(),
  grand_total: (json['grand_total'] as num?)?.toDouble(),
  comments: json['comments'] as String?,
  payment_status: (json['payment_status'] as num?)?.toInt(),
  restaurant_id: (json['restaurant_id'] as num?)?.toInt(),
  customer_id: (json['customer_id'] as num?)?.toInt(),
  customer_first_name: json['customer_first_name'] as String?,
  customer_last_name: json['customer_last_name'] as String?,
  mobile_no: json['mobile_no'] as String?,
  telephone_no: json['telephone_no'] as String?,
  order_transaction_status: (json['order_transaction_status'] as num?)?.toInt(),
  no_of_guest: (json['no_of_guest'] as num?)?.toInt(),
  is_sync: json['is_sync'] as bool?,
  order_date: json['order_date'] == null
      ? null
      : DateTime.parse(json['order_date'] as String),
  email: json['email'] as String?,
  address1: json['address1'] as String?,
  address2: json['address2'] as String?,
  town: json['town'] as String?,
  city: json['city'] as String?,
  postcode: json['postcode'] as String?,
  delivery_time: json['delivery_time'] == null
      ? null
      : DateTime.parse(json['delivery_time'] as String),
  bill_print_status: json['bill_print_status'] as bool?,
  platform_id: (json['platform_id'] as num?)?.toInt(),
  offer_text: json['offer_text'] as String?,
  discount_text: json['discount_text'] as String?,
  terminal_id: (json['terminal_id'] as num?)?.toInt(),
  orderToken: json['orderToken'] as String?,
  distance: (json['distance'] as num?)?.toDouble(),
  duration: json['duration'] as String?,
  order_status: json['order_status'] as String?,
  delivery_type: json['delivery_type'] as String?,
  order_reference: json['order_reference'] as String?,
  allergens: json['allergens'] as String?,
  reservation_id: json['reservation_id'] as String?,
  payment_message: json['payment_message'] as String?,
  is_marged: json['is_marged'] as bool?,
  hold_order: json['hold_order'] as bool?,
  is_allergen_asked: json['is_allergen_asked'] as bool?,
  delivery_time_range: json['delivery_time_range'] as String?,
);

Map<String, dynamic> _$ContactlessOrderTokenModelToJson(
  _ContactlessOrderTokenModel instance,
) => <String, dynamic>{
  'id': instance.id,
  '_id': instance.internalId,
  'server_id': instance.server_id,
  'status': instance.status,
  'restaurant_order_policy_id': instance.restaurant_order_policy_id,
  'total_amount': instance.total_amount,
  'grand_total': instance.grand_total,
  'comments': instance.comments,
  'payment_status': instance.payment_status,
  'restaurant_id': instance.restaurant_id,
  'customer_id': instance.customer_id,
  'customer_first_name': instance.customer_first_name,
  'customer_last_name': instance.customer_last_name,
  'mobile_no': instance.mobile_no,
  'telephone_no': instance.telephone_no,
  'order_transaction_status': instance.order_transaction_status,
  'no_of_guest': instance.no_of_guest,
  'is_sync': instance.is_sync,
  'order_date': instance.order_date?.toIso8601String(),
  'email': instance.email,
  'address1': instance.address1,
  'address2': instance.address2,
  'town': instance.town,
  'city': instance.city,
  'postcode': instance.postcode,
  'delivery_time': instance.delivery_time?.toIso8601String(),
  'bill_print_status': instance.bill_print_status,
  'platform_id': instance.platform_id,
  'offer_text': instance.offer_text,
  'discount_text': instance.discount_text,
  'terminal_id': instance.terminal_id,
  'orderToken': instance.orderToken,
  'distance': instance.distance,
  'duration': instance.duration,
  'order_status': instance.order_status,
  'delivery_type': instance.delivery_type,
  'order_reference': instance.order_reference,
  'allergens': instance.allergens,
  'reservation_id': instance.reservation_id,
  'payment_message': instance.payment_message,
  'is_marged': instance.is_marged,
  'hold_order': instance.hold_order,
  'is_allergen_asked': instance.is_allergen_asked,
  'delivery_time_range': instance.delivery_time_range,
};
