// ignore_for_file: non_constant_identifier_names
import 'package:freezed_annotation/freezed_annotation.dart';

part 'restaurant_settings_model.freezed.dart';
part 'restaurant_settings_model.g.dart';

@freezed
abstract class RestaurantSettingsModel with _$RestaurantSettingsModel {
  const factory RestaurantSettingsModel({
    int? id,
    int? restaurant_id,
    bool? show_confirmOrder,
    bool? alow_BillPrintOnConfirm,
    bool? enable_Confirmation_VoidDishStaff,
    bool? enable_Confirmation_Discount,
    bool? show_subCategory_Over_Favorite,
    bool? show_takeaway_Price_in_Kitchen,
    bool? show_dinein_Price_in_Kitchen,
    bool? enable_online_card_payment,
    bool? enable_alternative_language,
    int? kitchen_receipt_font_size,
    int? receipt_right_pade,
    bool? open_cashdraw_confirmationForStaff,
    String? billReceiptCustomMessage,
    bool? online_order_sync_active,
    bool? online_reservation_sync_active,
    bool? enable_closed_order_change,
    bool? order_alert,
    double? takeaway_order_discount_percent,
    int? font_receipt_right_pad,
    bool? show_payment_type_on_confirm,
    int? kitchen_receipt_top_pad,
    bool? enable_contactless_order,
    bool? alow_label_print,
    bool? active_delivery_charge,
    bool? active_restaurant_address_in_kitchen_recepit,
    int? default_logout_time,
    int? category_Columns,
    int? dish_Columns,
    bool? active_auto_bag_charge,
    double? takeaway_vat_rate_percent,
    double? dine_in_vat_rate_percent,
    bool? is_vat_active,
    bool? is_vat_amount_included,
    bool? allow_nfc_card_login,
    bool? enable_ePayment,
    bool? show_vat_on_receipt,
    bool? bill_print_on_instant_payment,
    bool? confirm_order_on_instant_payment,
    bool? is_allow_day_wise_menu,
    bool? is_ofline_terminal,
    bool? open_drawer_for_cash_payment,
    bool? open_drawer_for_card_payment,
    bool? show_new_item_printall_popup_on_confirmation_order,
    bool? tab_order_enabled,
    bool? serviceChargeFlag,
    bool? is_table_service_charge_fixed,
    String? table_service_charge_text,
    bool? enable_CardInfo,
    String? comp_item_text,
    bool? enable_find_order_sync,
    bool? enable_void_dish_print,
    bool? enable_cancel_order_print,
    bool? is_active_bill_print,
    bool? is_active_kitchen_print,
    bool? is_print_on_payment,
    bool? is_print_on_payment_cart,
    bool? quick_order_type_enabled,
    bool? dojo_payment_sense,
    bool? novopay_payment_sense,
    bool? is_kds_active,
    bool? active_multi_cashdrawer,
    bool? ask_allergen,
    bool? has_clock_in_out,
    bool? self_add_menu,
    bool? same_dine_in_takeaway_price,
    bool? print_alt_lang_kitchen,
    bool? is_amex_payment,
    bool? is_terminal_drinks_printer,
    int? course_1_Time,
    int? table_time,
    bool? pos_reservation_sync,
    bool? send_notification_on_sync,
    bool? main_ways,
    bool? all_together,
  }) = _RestaurantSettingsModel;

  factory RestaurantSettingsModel.fromJson(Map<String, dynamic> json) => _$RestaurantSettingsModelFromJson(json);
}
