// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'restaurant_settings_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_RestaurantSettingsModel _$RestaurantSettingsModelFromJson(
  Map<String, dynamic> json,
) => _RestaurantSettingsModel(
  id: (json['id'] as num?)?.toInt(),
  restaurant_id: (json['restaurant_id'] as num?)?.toInt(),
  show_confirmOrder: json['show_confirmOrder'] as bool?,
  alow_BillPrintOnConfirm: json['alow_BillPrintOnConfirm'] as bool?,
  enable_Confirmation_VoidDishStaff:
      json['enable_Confirmation_VoidDishStaff'] as bool?,
  enable_Confirmation_Discount: json['enable_Confirmation_Discount'] as bool?,
  show_subCategory_Over_Favorite:
      json['show_subCategory_Over_Favorite'] as bool?,
  show_takeaway_Price_in_Kitchen:
      json['show_takeaway_Price_in_Kitchen'] as bool?,
  show_dinein_Price_in_Kitchen: json['show_dinein_Price_in_Kitchen'] as bool?,
  enable_online_card_payment: json['enable_online_card_payment'] as bool?,
  enable_alternative_language: json['enable_alternative_language'] as bool?,
  kitchen_receipt_font_size: (json['kitchen_receipt_font_size'] as num?)
      ?.toInt(),
  receipt_right_pade: (json['receipt_right_pade'] as num?)?.toInt(),
  open_cashdraw_confirmationForStaff:
      json['open_cashdraw_confirmationForStaff'] as bool?,
  billReceiptCustomMessage: json['billReceiptCustomMessage'] as String?,
  online_order_sync_active: json['online_order_sync_active'] as bool?,
  online_reservation_sync_active:
      json['online_reservation_sync_active'] as bool?,
  enable_closed_order_change: json['enable_closed_order_change'] as bool?,
  order_alert: json['order_alert'] as bool?,
  takeaway_order_discount_percent:
      (json['takeaway_order_discount_percent'] as num?)?.toDouble(),
  font_receipt_right_pad: (json['font_receipt_right_pad'] as num?)?.toInt(),
  show_payment_type_on_confirm: json['show_payment_type_on_confirm'] as bool?,
  kitchen_receipt_top_pad: (json['kitchen_receipt_top_pad'] as num?)?.toInt(),
  enable_contactless_order: json['enable_contactless_order'] as bool?,
  alow_label_print: json['alow_label_print'] as bool?,
  active_delivery_charge: json['active_delivery_charge'] as bool?,
  active_restaurant_address_in_kitchen_recepit:
      json['active_restaurant_address_in_kitchen_recepit'] as bool?,
  default_logout_time: (json['default_logout_time'] as num?)?.toInt(),
  category_Columns: (json['category_Columns'] as num?)?.toInt(),
  dish_Columns: (json['dish_Columns'] as num?)?.toInt(),
  active_auto_bag_charge: json['active_auto_bag_charge'] as bool?,
  takeaway_vat_rate_percent: (json['takeaway_vat_rate_percent'] as num?)
      ?.toDouble(),
  dine_in_vat_rate_percent: (json['dine_in_vat_rate_percent'] as num?)
      ?.toDouble(),
  is_vat_active: json['is_vat_active'] as bool?,
  is_vat_amount_included: json['is_vat_amount_included'] as bool?,
  allow_nfc_card_login: json['allow_nfc_card_login'] as bool?,
  enable_ePayment: json['enable_ePayment'] as bool?,
  show_vat_on_receipt: json['show_vat_on_receipt'] as bool?,
  bill_print_on_instant_payment: json['bill_print_on_instant_payment'] as bool?,
  confirm_order_on_instant_payment:
      json['confirm_order_on_instant_payment'] as bool?,
  is_allow_day_wise_menu: json['is_allow_day_wise_menu'] as bool?,
  is_ofline_terminal: json['is_ofline_terminal'] as bool?,
  open_drawer_for_cash_payment: json['open_drawer_for_cash_payment'] as bool?,
  open_drawer_for_card_payment: json['open_drawer_for_card_payment'] as bool?,
  show_new_item_printall_popup_on_confirmation_order:
      json['show_new_item_printall_popup_on_confirmation_order'] as bool?,
  tab_order_enabled: json['tab_order_enabled'] as bool?,
  serviceChargeFlag: json['serviceChargeFlag'] as bool?,
  is_table_service_charge_fixed: json['is_table_service_charge_fixed'] as bool?,
  table_service_charge_text: json['table_service_charge_text'] as String?,
  enable_CardInfo: json['enable_CardInfo'] as bool?,
  comp_item_text: json['comp_item_text'] as String?,
  enable_find_order_sync: json['enable_find_order_sync'] as bool?,
  enable_void_dish_print: json['enable_void_dish_print'] as bool?,
  enable_cancel_order_print: json['enable_cancel_order_print'] as bool?,
  is_active_bill_print: json['is_active_bill_print'] as bool?,
  is_active_kitchen_print: json['is_active_kitchen_print'] as bool?,
  is_print_on_payment: json['is_print_on_payment'] as bool?,
  is_print_on_payment_cart: json['is_print_on_payment_cart'] as bool?,
  quick_order_type_enabled: json['quick_order_type_enabled'] as bool?,
  dojo_payment_sense: json['dojo_payment_sense'] as bool?,
  novopay_payment_sense: json['novopay_payment_sense'] as bool?,
  is_kds_active: json['is_kds_active'] as bool?,
  active_multi_cashdrawer: json['active_multi_cashdrawer'] as bool?,
  ask_allergen: json['ask_allergen'] as bool?,
  has_clock_in_out: json['has_clock_in_out'] as bool?,
  self_add_menu: json['self_add_menu'] as bool?,
  same_dine_in_takeaway_price: json['same_dine_in_takeaway_price'] as bool?,
  print_alt_lang_kitchen: json['print_alt_lang_kitchen'] as bool?,
  is_amex_payment: json['is_amex_payment'] as bool?,
  is_terminal_drinks_printer: json['is_terminal_drinks_printer'] as bool?,
  course_1_Time: (json['course_1_Time'] as num?)?.toInt(),
  table_time: (json['table_time'] as num?)?.toInt(),
  pos_reservation_sync: json['pos_reservation_sync'] as bool?,
  send_notification_on_sync: json['send_notification_on_sync'] as bool?,
  main_ways: json['main_ways'] as bool?,
  all_together: json['all_together'] as bool?,
);

Map<String, dynamic> _$RestaurantSettingsModelToJson(
  _RestaurantSettingsModel instance,
) => <String, dynamic>{
  'id': instance.id,
  'restaurant_id': instance.restaurant_id,
  'show_confirmOrder': instance.show_confirmOrder,
  'alow_BillPrintOnConfirm': instance.alow_BillPrintOnConfirm,
  'enable_Confirmation_VoidDishStaff':
      instance.enable_Confirmation_VoidDishStaff,
  'enable_Confirmation_Discount': instance.enable_Confirmation_Discount,
  'show_subCategory_Over_Favorite': instance.show_subCategory_Over_Favorite,
  'show_takeaway_Price_in_Kitchen': instance.show_takeaway_Price_in_Kitchen,
  'show_dinein_Price_in_Kitchen': instance.show_dinein_Price_in_Kitchen,
  'enable_online_card_payment': instance.enable_online_card_payment,
  'enable_alternative_language': instance.enable_alternative_language,
  'kitchen_receipt_font_size': instance.kitchen_receipt_font_size,
  'receipt_right_pade': instance.receipt_right_pade,
  'open_cashdraw_confirmationForStaff':
      instance.open_cashdraw_confirmationForStaff,
  'billReceiptCustomMessage': instance.billReceiptCustomMessage,
  'online_order_sync_active': instance.online_order_sync_active,
  'online_reservation_sync_active': instance.online_reservation_sync_active,
  'enable_closed_order_change': instance.enable_closed_order_change,
  'order_alert': instance.order_alert,
  'takeaway_order_discount_percent': instance.takeaway_order_discount_percent,
  'font_receipt_right_pad': instance.font_receipt_right_pad,
  'show_payment_type_on_confirm': instance.show_payment_type_on_confirm,
  'kitchen_receipt_top_pad': instance.kitchen_receipt_top_pad,
  'enable_contactless_order': instance.enable_contactless_order,
  'alow_label_print': instance.alow_label_print,
  'active_delivery_charge': instance.active_delivery_charge,
  'active_restaurant_address_in_kitchen_recepit':
      instance.active_restaurant_address_in_kitchen_recepit,
  'default_logout_time': instance.default_logout_time,
  'category_Columns': instance.category_Columns,
  'dish_Columns': instance.dish_Columns,
  'active_auto_bag_charge': instance.active_auto_bag_charge,
  'takeaway_vat_rate_percent': instance.takeaway_vat_rate_percent,
  'dine_in_vat_rate_percent': instance.dine_in_vat_rate_percent,
  'is_vat_active': instance.is_vat_active,
  'is_vat_amount_included': instance.is_vat_amount_included,
  'allow_nfc_card_login': instance.allow_nfc_card_login,
  'enable_ePayment': instance.enable_ePayment,
  'show_vat_on_receipt': instance.show_vat_on_receipt,
  'bill_print_on_instant_payment': instance.bill_print_on_instant_payment,
  'confirm_order_on_instant_payment': instance.confirm_order_on_instant_payment,
  'is_allow_day_wise_menu': instance.is_allow_day_wise_menu,
  'is_ofline_terminal': instance.is_ofline_terminal,
  'open_drawer_for_cash_payment': instance.open_drawer_for_cash_payment,
  'open_drawer_for_card_payment': instance.open_drawer_for_card_payment,
  'show_new_item_printall_popup_on_confirmation_order':
      instance.show_new_item_printall_popup_on_confirmation_order,
  'tab_order_enabled': instance.tab_order_enabled,
  'serviceChargeFlag': instance.serviceChargeFlag,
  'is_table_service_charge_fixed': instance.is_table_service_charge_fixed,
  'table_service_charge_text': instance.table_service_charge_text,
  'enable_CardInfo': instance.enable_CardInfo,
  'comp_item_text': instance.comp_item_text,
  'enable_find_order_sync': instance.enable_find_order_sync,
  'enable_void_dish_print': instance.enable_void_dish_print,
  'enable_cancel_order_print': instance.enable_cancel_order_print,
  'is_active_bill_print': instance.is_active_bill_print,
  'is_active_kitchen_print': instance.is_active_kitchen_print,
  'is_print_on_payment': instance.is_print_on_payment,
  'is_print_on_payment_cart': instance.is_print_on_payment_cart,
  'quick_order_type_enabled': instance.quick_order_type_enabled,
  'dojo_payment_sense': instance.dojo_payment_sense,
  'novopay_payment_sense': instance.novopay_payment_sense,
  'is_kds_active': instance.is_kds_active,
  'active_multi_cashdrawer': instance.active_multi_cashdrawer,
  'ask_allergen': instance.ask_allergen,
  'has_clock_in_out': instance.has_clock_in_out,
  'self_add_menu': instance.self_add_menu,
  'same_dine_in_takeaway_price': instance.same_dine_in_takeaway_price,
  'print_alt_lang_kitchen': instance.print_alt_lang_kitchen,
  'is_amex_payment': instance.is_amex_payment,
  'is_terminal_drinks_printer': instance.is_terminal_drinks_printer,
  'course_1_Time': instance.course_1_Time,
  'table_time': instance.table_time,
  'pos_reservation_sync': instance.pos_reservation_sync,
  'send_notification_on_sync': instance.send_notification_on_sync,
  'main_ways': instance.main_ways,
  'all_together': instance.all_together,
};
